# Generated by Django 6.1.1 on 2026-09-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_id', models.UUIDField(db_index=True, unique=True)),
                ('essential', models.BooleanField(default=True)),
                ('analytics', models.BooleanField(default=False)),
                ('marketing', models.BooleanField(default=False)),
                ('decided_at', models.DateTimeField()),
                ('policy_version', models.CharField(max_length=32)),
                ('policy_url', models.URLField(max_length=500)),
                ('source', models.CharField(default='cookie-banner', max_length=64)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-received_at',),
            },
        ),
    ]
